version: "3.7"

networks:
  postgres_network:
    driver: bridge
    name: postgres_network

services:
  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    env_file:
      - postgres/.env
    restart: on-failure
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - postgres_network

  backend_service:
    depends_on:
      - postgres
    restart: always
    build: .
    ports:
    - "${APP_PORT}:${APP_PORT}"
    volumes:
    - .:/data/app
    - /data/app/node_modules
    env_file: .env
    networks:
      - postgres_network

  pg-admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pg-admin:/root/.pg-admin
    ports:
      - "${PGADMIN_PORT:-9999}:80"
    networks:
      - postgres_network
    links:
      - postgres:pgsql-server
    restart: unless-stopped

volumes:
  dbdata:
  pg-admin:
