version: "3.7"

networks:
  nodemysql:
    driver: bridge
    name: nodemysql

services:
  db:
    image: mysql:5.7
    container_name: ${DB_HOST}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: on-failure
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - nodemysql

  backend_service:
    depends_on:
      - db
    restart: always
    build: .
    ports:
    - "${APP_PORT}:${APP_PORT}"
    volumes:
    - .:/data/app
    - /data/app/node_modules
    env_file: .env
    networks:
      - nodemysql

  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:${DB_HOST}
    depends_on:
      - db
    ports:
      - "9999:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    networks:
      - nodemysql

volumes:
  dbdata:

