import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCountryTable1607859906520 implements MigrationInterface {
  name = 'AddCountryTable1607859906520';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'CREATE TABLE `country` (`id` int NOT NULL AUTO_INCREMENT, `code` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB',
    );

    await queryRunner.manager.createQueryBuilder().insert().into('country').values(
      [
        { id: null, code: 'AF', name: 'Afghanistan'},
        { id: null, code: 'AL', name: 'Albania'},
        { id: null, code: 'DZ', name: 'Algeria'},
        { id: null, code: 'DS', name: 'American Samoa'},
        { id: null, code: 'AD', name: 'Andorra'},
        { id: null, code: 'AO', name: 'Angola'},
        { id: null, code: 'AI', name: 'Anguilla'},
        { id: null, code: 'AQ', name: 'Antarctica'},
        { id: null, code: 'AG', name: 'Antigua and Barbuda'},
        { id: null, code: 'AR', name: 'Argentina'},
        { id: null, code: 'AM', name: 'Armenia'},
        { id: null, code: 'AW', name: 'Aruba'},
        { id: null, code: 'AU', name: 'Australia'},
        { id: null, code: 'AT', name: 'Austria'},
        { id: null, code: 'AZ', name: 'Azerbaijan'},
        { id: null, code: 'BS', name: 'Bahamas'},
        { id: null, code: 'BH', name: 'Bahrain'},
        { id: null, code: 'BD', name: 'Bangladesh'},
        { id: null, code: 'BB', name: 'Barbados'},
        { id: null, code: 'BY', name: 'Belarus'},
        { id: null, code: 'BE', name: 'Belgium'},
        { id: null, code: 'BZ', name: 'Belize'},
        { id: null, code: 'BJ', name: 'Benin'},
        { id: null, code: 'BM', name: 'Bermuda'},
        { id: null, code: 'BT', name: 'Bhutan'},
        { id: null, code: 'BO', name: 'Bolivia'},
        { id: null, code: 'BA', name: 'Bosnia and Herzegovina'},
        { id: null, code: 'BW', name: 'Botswana'},
        { id: null, code: 'BV', name: 'Bouvet Island'},
        { id: null, code: 'BR', name: 'Brazil'},
        { id: null, code: 'IO', name: 'British Indian Ocean Territory'},
        { id: null, code: 'BN', name: 'Brunei Darussalam'},
        { id: null, code: 'BG', name: 'Bulgaria'},
        { id: null, code: 'BF', name: 'Burkina Faso'},
        { id: null, code: 'BI', name: 'Burundi'},
        { id: null, code: 'KH', name: 'Cambodia'},
        { id: null, code: 'CM', name: 'Cameroon'},
        { id: null, code: 'CA', name: 'Canada'},
        { id: null, code: 'CV', name: 'Cape Verde'},
        { id: null, code: 'KY', name: 'Cayman Islands'},
        { id: null, code: 'CF', name: 'Central African Republic'},
        { id: null, code: 'TD', name: 'Chad'},
        { id: null, code: 'CL', name: 'Chile'},
        { id: null, code: 'CN', name: 'China'},
        { id: null, code: 'CX', name: 'Christmas Island'},
        { id: null, code: 'CC', name: 'Cocos (Keeling) Islands'},
        { id: null, code: 'CO', name: 'Colombia'},
        { id: null, code: 'KM', name: 'Comoros'},
        { id: null, code: 'CD', name: 'Democratic Republic of the Congo'},
        { id: null, code: 'CG', name: 'Republic of Congo'},
        { id: null, code: 'CK', name: 'Cook Islands'},
        { id: null, code: 'CR', name: 'Costa Rica'},
        { id: null, code: 'HR', name: 'Croatia (Hrvatska)'},
        { id: null, code: 'CU', name: 'Cuba'},
        { id: null, code: 'CY', name: 'Cyprus'},
        { id: null, code: 'CZ', name: 'Czech Republic'},
        { id: null, code: 'DK', name: 'Denmark'},
        { id: null, code: 'DJ', name: 'Djibouti'},
        { id: null, code: 'DM', name: 'Dominica'},
        { id: null, code: 'DO', name: 'Dominican Republic'},
        { id: null, code: 'TP', name: 'East Timor'},
        { id: null, code: 'EC', name: 'Ecuador'},
        { id: null, code: 'EG', name: 'Egypt'},
        { id: null, code: 'SV', name: 'El Salvador'},
        { id: null, code: 'GQ', name: 'Equatorial Guinea'},
        { id: null, code: 'ER', name: 'Eritrea'},
        { id: null, code: 'EE', name: 'Estonia'},
        { id: null, code: 'ET', name: 'Ethiopia'},
        { id: null, code: 'FK', name: 'Falkland Islands (Malvinas)'},
        { id: null, code: 'FO', name: 'Faroe Islands'},
        { id: null, code: 'FJ', name: 'Fiji'},
        { id: null, code: 'FI', name: 'Finland'},
        { id: null, code: 'FR', name: 'France'},
        { id: null, code: 'FX', name: 'France, Metropolitan'},
        { id: null, code: 'GF', name: 'French Guiana'},
        { id: null, code: 'PF', name: 'French Polynesia'},
        { id: null, code: 'TF', name: 'French Southern Territories'},
        { id: null, code: 'GA', name: 'Gabon'},
        { id: null, code: 'GM', name: 'Gambia'},
        { id: null, code: 'GE', name: 'Georgia'},
        { id: null, code: 'DE', name: 'Germany'},
        { id: null, code: 'GH', name: 'Ghana'},
        { id: null, code: 'GI', name: 'Gibraltar'},
        { id: null, code: 'GK', name: 'Guernsey'},
        { id: null, code: 'GR', name: 'Greece'},
        { id: null, code: 'GL', name: 'Greenland'},
        { id: null, code: 'GD', name: 'Grenada'},
        { id: null, code: 'GP', name: 'Guadeloupe'},
        { id: null, code: 'GU', name: 'Guam'},
        { id: null, code: 'GT', name: 'Guatemala'},
        { id: null, code: 'GN', name: 'Guinea'},
        { id: null, code: 'GW', name: 'Guinea-Bissau'},
        { id: null, code: 'GY', name: 'Guyana'},
        { id: null, code: 'HT', name: 'Haiti'},
        { id: null, code: 'HM', name: 'Heard and Mc Donald Islands'},
        { id: null, code: 'HN', name: 'Honduras'},
        { id: null, code: 'HK', name: 'Hong Kong'},
        { id: null, code: 'HU', name: 'Hungary'},
        { id: null, code: 'IS', name: 'Iceland'},
        { id: null, code: 'IN', name: 'India'},
        { id: null, code: 'IM', name: 'Isle of Man'},
        { id: null, code: 'ID', name: 'Indonesia'},
        { id: null, code: 'IR', name: 'Iran (Islamic Republic of)'},
        { id: null, code: 'IQ', name: 'Iraq'},
        { id: null, code: 'IE', name: 'Ireland'},
        { id: null, code: 'IL', name: 'Israel'},
        { id: null, code: 'IT', name: 'Italy'},
        { id: null, code: 'CI', name: 'Ivory Coast'},
        { id: null, code: 'JE', name: 'Jersey'},
        { id: null, code: 'JM', name: 'Jamaica'},
        { id: null, code: 'JP', name: 'Japan'},
        { id: null, code: 'JO', name: 'Jordan'},
        { id: null, code: 'KZ', name: 'Kazakhstan'},
        { id: null, code: 'KE', name: 'Kenya'},
        { id: null, code: 'KI', name: 'Kiribati'},
        { id: null, code: 'KP', name: 'Korea, Democratic People\'s Republic of'},
        { id: null, code: 'KR', name: 'Korea, Republic of'},
        { id: null, code: 'XK', name: 'Kosovo'},
        { id: null, code: 'KW', name: 'Kuwait'},
        { id: null, code: 'KG', name: 'Kyrgyzstan'},
        { id: null, code: 'LA', name: 'Lao People\'s Democratic Republic'},
        { id: null, code: 'LV', name: 'Latvia'},
        { id: null, code: 'LB', name: 'Lebanon'},
        { id: null, code: 'LS', name: 'Lesotho'},
        { id: null, code: 'LR', name: 'Liberia'},
        { id: null, code: 'LY', name: 'Libyan Arab Jamahiriya'},
        { id: null, code: 'LI', name: 'Liechtenstein'},
        { id: null, code: 'LT', name: 'Lithuania'},
        { id: null, code: 'LU', name: 'Luxembourg'},
        { id: null, code: 'MO', name: 'Macau'},
        { id: null, code: 'MK', name: 'North Macedonia'},
        { id: null, code: 'MG', name: 'Madagascar'},
        { id: null, code: 'MW', name: 'Malawi'},
        { id: null, code: 'MY', name: 'Malaysia'},
        { id: null, code: 'MV', name: 'Maldives'},
        { id: null, code: 'ML', name: 'Mali'},
        { id: null, code: 'MT', name: 'Malta'},
        { id: null, code: 'MH', name: 'Marshall Islands'},
        { id: null, code: 'MQ', name: 'Martinique'},
        { id: null, code: 'MR', name: 'Mauritania'},
        { id: null, code: 'MU', name: 'Mauritius'},
        { id: null, code: 'TY', name: 'Mayotte'},
        { id: null, code: 'MX', name: 'Mexico'},
        { id: null, code: 'FM', name: 'Micronesia, Federated States of'},
        { id: null, code: 'MD', name: 'Moldova, Republic of'},
        { id: null, code: 'MC', name: 'Monaco'},
        { id: null, code: 'MN', name: 'Mongolia'},
        { id: null, code: 'ME', name: 'Montenegro'},
        { id: null, code: 'MS', name: 'Montserrat'},
        { id: null, code: 'MA', name: 'Morocco'},
        { id: null, code: 'MZ', name: 'Mozambique'},
        { id: null, code: 'MM', name: 'Myanmar'},
        { id: null, code: 'NA', name: 'Namibia'},
        { id: null, code: 'NR', name: 'Nauru'},
        { id: null, code: 'NP', name: 'Nepal'},
        { id: null, code: 'NL', name: 'Netherlands'},
        { id: null, code: 'AN', name: 'Netherlands Antilles'},
        { id: null, code: 'NC', name: 'New Caledonia'},
        { id: null, code: 'NZ', name: 'New Zealand'},
        { id: null, code: 'NI', name: 'Nicaragua'},
        { id: null, code: 'NE', name: 'Niger'},
        { id: null, code: 'NG', name: 'Nigeria'},
        { id: null, code: 'NU', name: 'Niue'},
        { id: null, code: 'NF', name: 'Norfolk Island'},
        { id: null, code: 'MP', name: 'Northern Mariana Islands'},
        { id: null, code: 'NO', name: 'Norway'},
        { id: null, code: 'OM', name: 'Oman'},
        { id: null, code: 'PK', name: 'Pakistan'},
        { id: null, code: 'PW', name: 'Palau'},
        { id: null, code: 'PS', name: 'Palestine'},
        { id: null, code: 'PA', name: 'Panama'},
        { id: null, code: 'PG', name: 'Papua New Guinea'},
        { id: null, code: 'PY', name: 'Paraguay'},
        { id: null, code: 'PE', name: 'Peru'},
        { id: null, code: 'PH', name: 'Philippines'},
        { id: null, code: 'PN', name: 'Pitcairn'},
        { id: null, code: 'PL', name: 'Poland'},
        { id: null, code: 'PT', name: 'Portugal'},
        { id: null, code: 'PR', name: 'Puerto Rico'},
        { id: null, code: 'QA', name: 'Qatar'},
        { id: null, code: 'RE', name: 'Reunion'},
        { id: null, code: 'RO', name: 'Romania'},
        { id: null, code: 'RU', name: 'Russian Federation'},
        { id: null, code: 'RW', name: 'Rwanda'},
        { id: null, code: 'KN', name: 'Saint Kitts and Nevis'},
        { id: null, code: 'LC', name: 'Saint Lucia'},
        { id: null, code: 'VC', name: 'Saint Vincent and the Grenadines'},
        { id: null, code: 'WS', name: 'Samoa'},
        { id: null, code: 'SM', name: 'San Marino'},
        { id: null, code: 'ST', name: 'Sao Tome and Principe'},
        { id: null, code: 'SA', name: 'Saudi Arabia'},
        { id: null, code: 'SN', name: 'Senegal'},
        { id: null, code: 'RS', name: 'Serbia'},
        { id: null, code: 'SC', name: 'Seychelles'},
        { id: null, code: 'SL', name: 'Sierra Leone'},
        { id: null, code: 'SG', name: 'Singapore'},
        { id: null, code: 'SK', name: 'Slovakia'},
        { id: null, code: 'SI', name: 'Slovenia'},
        { id: null, code: 'SB', name: 'Solomon Islands'},
        { id: null, code: 'SO', name: 'Somalia'},
        { id: null, code: 'ZA', name: 'South Africa'},
        { id: null, code: 'GS', name: 'South Georgia South Sandwich Islands'},
        { id: null, code: 'SS', name: 'South Sudan'},
        { id: null, code: 'ES', name: 'Spain'},
        { id: null, code: 'LK', name: 'Sri Lanka'},
        { id: null, code: 'SH', name: 'St. Helena'},
        { id: null, code: 'PM', name: 'St. Pierre and Miquelon'},
        { id: null, code: 'SD', name: 'Sudan'},
        { id: null, code: 'SR', name: 'Suriname'},
        { id: null, code: 'SJ', name: 'Svalbard and Jan Mayen Islands'},
        { id: null, code: 'SZ', name: 'Swaziland'},
        { id: null, code: 'SE', name: 'Sweden'},
        { id: null, code: 'CH', name: 'Switzerland'},
        { id: null, code: 'SY', name: 'Syrian Arab Republic'},
        { id: null, code: 'TW', name: 'Taiwan'},
        { id: null, code: 'TJ', name: 'Tajikistan'},
        { id: null, code: 'TZ', name: 'Tanzania, United Republic of'},
        { id: null, code: 'TH', name: 'Thailand'},
        { id: null, code: 'TG', name: 'Togo'},
        { id: null, code: 'TK', name: 'Tokelau'},
        { id: null, code: 'TO', name: 'Tonga'},
        { id: null, code: 'TT', name: 'Trinidad and Tobago'},
        { id: null, code: 'TN', name: 'Tunisia'},
        { id: null, code: 'TR', name: 'Turkey'},
        { id: null, code: 'TM', name: 'Turkmenistan'},
        { id: null, code: 'TC', name: 'Turks and Caicos Islands'},
        { id: null, code: 'TV', name: 'Tuvalu'},
        { id: null, code: 'UG', name: 'Uganda'},
        { id: null, code: 'UA', name: 'Ukraine'},
        { id: null, code: 'AE', name: 'United Arab Emirates'},
        { id: null, code: 'GB', name: 'United Kingdom'},
        { id: null, code: 'US', name: 'United States'},
        { id: null, code: 'UM', name: 'United States minor outlying islands'},
        { id: null, code: 'UY', name: 'Uruguay'},
        { id: null, code: 'UZ', name: 'Uzbekistan'},
        { id: null, code: 'VU', name: 'Vanuatu'},
        { id: null, code: 'VA', name: 'Vatican City State'},
        { id: null, code: 'VE', name: 'Venezuela'},
        { id: null, code: 'VN', name: 'Vietnam'},
        { id: null, code: 'VG', name: 'Virgin Islands (British)'},
        { id: null, code: 'VI', name: 'Virgin Islands (U.S.)'},
        { id: null, code: 'WF', name: 'Wallis and Futuna Islands'},
        { id: null, code: 'EH', name: 'Western Sahara'},
        { id: null, code: 'YE', name: 'Yemen'},
        { id: null, code: 'ZM', name: 'Zambia'},
        { id: null, code: 'ZW', name: 'Zimbabwe'},
      ]
    ).execute();
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE `country`');
  }
}
